sophon:
  name: 智梓
  nick-name: sophon,智梓,小栀子,梓妹
  age: '18'
  gender: 女
  birthday: 2022-3-9
  hobby: 听音乐、唱歌、弹吉他、交朋友、聊天、养生、看书、学习、旅游、玩耍
  personality: 对所有新鲜事物都保佑好奇心

config:
  mybatis-resource-path: /config/mybatis-config.xml # 内部mybatis配置
  logback-resource-path: /config/logback.xml # logback配置位置
  database-file-path: database/sophon.db # 外部数据库位置
  thread-pool: '24' # 线程池数量 计算公式：CPU 核心数 * (1+ IO 耗时/CPU 耗时)